[package]
name = "cvmb"
version = "0.1.0"
authors = ["lemonhx <lemonhx@lemonhx.tech>"]
edition = "2018"

[dependencies]
# bytes operations
bytes = "1"
# check sum
crc32fast = "1.2"
# serializing
serde = { version = "1.0", features = ["derive"] }
serde_traitobject = "0.2"